"""add phone number

Revision ID: 934fa6a2dbf3
Revises: 1cc1061abb9d
Create Date: 2022-06-22 16:01:56.389259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934fa6a2dbf3'
down_revision = '1cc1061abb9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
